{
 "title": "Connection Metrics",
 "tags": [
  "dhruva",
  "devops"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment Filter",
    "query": "show tag values from \"dhruva.connection\" with key = \"environment\""
   }
  ]
 },
 "panels": [
  { "title": "Udp Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UDP Channel Statistics",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_environment {Direction: $tag_direction,  State: $tag_connectionState}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" = 'UDP' AND $timeFilter GROUP BY time($__interval), \"direction\", \"connectionState\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Udp Active channels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Instance: $tag_instanceName  - Transport: $tag_transport -  Direction: $tag_direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.connection\" WHERE \"servicename\" = 'dhruva' AND \"transport\" = 'UDP' AND \"environment\" =~ /$env/ AND $timeFilter GROUP BY environment, \"instanceName\", \"transport\", \"direction\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "TCP/TLS connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "TCP connections",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_environment {Direction: $tag_direction,  State: $tag_connectionState}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"id\")) FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" = 'TCP' AND $timeFilter GROUP BY  \"direction\", \"connectionState\", \"environment\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "TLS connections",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 11, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_environment {Direction: $tag_direction,  State: $tag_connectionState}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"id\")) FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" = 'TLS' AND $timeFilter GROUP BY  \"direction\", \"connectionState\", \"environment\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Active Connections by Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Instance: $tag_instanceName  - Transport: $tag_transport -  Direction: $tag_direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"id\")) FROM \"dhruva.connection\" WHERE \"servicename\" = 'dhruva' AND \"transport\" != 'UDP' AND \"environment\" =~ /$env/ AND $timeFilter GROUP BY environment, \"instanceName\", \"transport\", \"direction\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Connection failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Connection failure info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"transport\", \"localAddress\", \"localPort\", \"remoteAddress\", \"remotePort\", \"errorMessage\" FROM \"dhruva.connection.failure\" WHERE \"environment\" =~ /$env/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disconnected connections info",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"id\", \"localAddress\", \"localPort\", \"remoteAddress\", \"remotePort\", \"direction\", \"transport\", \"connectionState\" FROM \"dhruva.connection\" where \"connectionState\"  = 'DISCONNECTED' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}