{
 "title": "Connection Metrices - DSB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment Filter", "query": "sip-dev,wsjcint01" },
   {
    "name": "transport",
    "label": "Transport",
    "query": "show tag values from \"dhruva.connection\" with key = \"transport\""
   }
  ]
 },
 "panels": [
  {
   "title": "TLS connections",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_environment {Direction: $tag_direction,  State: $tag_connectionState}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" = 'TLS' AND $timeFilter GROUP BY time($__interval), \"direction\", \"connectionState\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "UDP connections",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_environment {Direction: $tag_direction,  State: $tag_connectionState}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" = 'UDP' AND $timeFilter GROUP BY time($__interval), \"direction\", \"connectionState\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "TCP connections",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_environment {Direction: $tag_direction,  State: $tag_connectionState}",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" = 'TCP' AND $timeFilter GROUP BY time($__interval), \"direction\", \"connectionState\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Connection details",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"localIp\", \"localPort\", \"remoteIp\", \"remotePort\", \"direction\", \"transport\", \"connectionState\"FROM \"dhruva.connection\" WHERE \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}