{
 "title": "Dhruva Application JVM Metrics",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "tags": [ "dhruva" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment Name",
    "query": "show tag values from \"jvm_memory_used\" with key=\"environment\" where \"servicename\" = 'dhruva'"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "SHOW TAG values from \"jvm_memory_used\" with key = \"instancename\" where \"environment\" =~ /$environment/ and time >= now()"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"process_uptime\" WHERE  \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"process_start_time\" WHERE  \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "sum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Non Heap used",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "sum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'nonheap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'heap' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'nonheap'   and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'nonheap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE  \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE    \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE   \"servicename\" = 'dhruva'  and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM memory pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "JVM heap usage(by id)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "G1 Old Gen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT (\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'   and \"id\" = 'G1\\\\ Old\\\\ Gen' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "G1 Eden Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'   and \"id\" = 'G1\\\\ Eden\\\\ Space' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "G1 Survivor Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'   and \"id\" = 'G1\\\\ Survivor\\\\ Space' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM nonheap usage(by Id)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Metaspace",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'Metaspace' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Compressed Class Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'Compressed\\\\ Class\\\\ Space' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Code Cache",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'Code\\\\ Cache' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Code Heap 'non-nmethods'",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'CodeHeap\\\\ \\'non-nmethods\\'' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM Misc Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Process CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"process_cpu_usage\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "System CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "query": "SELECT (\"value\") FROM \"system_cpu_usage\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "Mean Usage(1h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT mean(\"value\") FROM \"process_cpu_usage\" WHERE  \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and  $timeFilter GROUP BY time(1h) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "System load avg (1m)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"system_load_average_1m\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CPU count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"system_cpu_count\" WHERE   \"servicename\" = 'dhruva'  and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "Live",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"jvm_threads_live\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Daemon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"jvm_threads_daemon\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"jvm_threads_peak\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'blocked' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'new' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Waiting",
     "measurement": "jvm_threads_states",
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE (\"state\" = 'waiting' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "Runnable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'runnable' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Terminated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'terminated' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "timed-waiting",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'timed-waiting' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "gc_pause_mean{{cause: $tag_cause, action : $tag_action}}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"jvm_gc_pause\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter GROUP BY time(1m), \"action\" , \"cause\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" }
     ],
     "measurement": "jvm.gc.summary",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(mean(\"duration\") , 1s)FROM \"jvm.gc.summary\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ AND $timeFilter GROUP BY time(1h), \"action\", \"cause\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Allocated Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT sum(\"value\") FROM \"jvm_gc_memory_allocated\" WHERE (\"servicename\" = 'dhruva') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_gc_memory_promoted\" WHERE (\"servicename\" = 'dhruva') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}