{
 "title": "Dhruva Application JVM Metrics",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "dhruva" },
   {
    "name": "environment",
    "label": "Environment Name",
    "query": "show tag values from \"jvm_memory_used\" with key=\"environment\" where \"servicename\" = 'dhruva'"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "SHOW TAG values from \"jvm_memory_used\" with key = \"instancename\" where \"environment\" =~ /$environment/ and time >= now()"
   }
  ]
 },
 "panels": [
  { "title": "JVM Memory ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'heap' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'nonheap'   and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'nonheap'  and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE  \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "committed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE    \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE   \"servicename\" = 'dhruva'  and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM memory pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM heap usage(by id)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "G1 Old Gen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_used",
     "query": "SELECT (\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'   and \"id\" = 'G1\\\\ Old\\\\ Gen' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "G1 Eden Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'   and \"id\" = 'G1\\\\ Eden\\\\ Space' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "G1 Survivor Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap'   and \"id\" = 'G1\\\\ Survivor\\\\ Space' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JVM nonheap usage(by Id)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Metaspace",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'Metaspace' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Compressed Class Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'Compressed\\\\ Class\\\\ Space' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Code Cache",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'Code\\\\ Cache' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Code Heap 'non-nmethods'",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"jvm_memory_used\" WHERE (\"area\" = 'nonheap'  and \"id\" = 'CodeHeap\\\\ \\'non-nmethods\\'' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JVM Misc Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Process CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"process_cpu_usage\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "System CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "query": "SELECT (\"value\") FROM \"system_cpu_usage\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and  $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "Mean Usage(1h)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\nSELECT mean(\"value\") FROM \"process_cpu_usage\" WHERE  \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and  $timeFilter GROUP BY time(1h) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "System load avg (1m)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"system_load_average_1m\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CPU count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"system_cpu_count\" WHERE   \"servicename\" = 'dhruva'  and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Thread Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "Live",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"jvm_threads_live\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Daemon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"jvm_threads_daemon\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/  and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT(\"value\") FROM \"jvm_threads_peak\" WHERE \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ and $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'blocked' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'new' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Waiting",
     "measurement": "jvm_threads_states",
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE (\"state\" = 'waiting' and \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "Runnable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'runnable' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Terminated",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'terminated' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "timed-waiting",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (\"value\") FROM \"jvm_threads_states\" WHERE  (\"state\" = 'timed-waiting' AND \"servicename\" = 'dhruva' and \"environment\" =~ /$environment/ and \"instancename\"=~ /$instance/ ) and $timeFilter \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "gc_pause_mean{{cause: $tag_cause, action : $tag_action}}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"jvm_gc_pause\" WHERE \"servicename\" = 'dhruva' and $timeFilter GROUP BY time(1m), \"action\" , \"cause\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "action" ], "type": "tag" },
      { "params": [ "cause" ], "type": "tag" }
     ],
     "measurement": "jvm.gc.summary",
     "query": "SELECT NON_NEGATIVE_DERIVATIVE(mean(\"duration\") , 1s)FROM \"jvm.gc.summary\" WHERE (\"servicename\" = 'dhruva' ) AND $timeFilter GROUP BY time(1h), \"action\", \"cause\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Allocated Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_gc_memory_allocated",
     "query": "SELECT sum(\"value\") FROM \"jvm_gc_memory_allocated\" WHERE (\"servicename\" = 'dhruva') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "servicename", "operator": "=", "value": "dhruva" }
     ]
    },
    {
     "alias": "Promoted Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"jvm_gc_memory_promoted\" WHERE (\"servicename\" = 'dhruva') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time{application=\"$application\", instance=\"$instance\"}*1000"
      }
     ]
    },
    {
     "title": "Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Heap used with influx",
     "type": "blackmirror1-singlestat-math-panel",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 49 },
     "format": "percent",
     "valueName": "total",
     "targets": [
      {
       "alias": "used",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap' ) AND $timeFilter GROUP BY time($__interval) fill(null)"
      },
      {
       "alias": "max",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap' ) AND $timeFilter GROUP BY time($__interval) fill(null)"
      }
     ]
    },
    {
     "title": "Non-Heap used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
       "legendFormat": "HTTP - AVG"
      },
      {
       "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
       "legendFormat": "HTTP - MAX"
      }
     ]
    },
    {
     "title": "Utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_busy_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "TOMCAT - BSY"
      },
      {
       "expr": "tomcat_threads_current_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "TOMCAT - CUR"
      },
      {
       "expr": "tomcat_threads_config_max_threads{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "TOMCAT - MAX"
      },
      {
       "expr": "jetty_threads_busy{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "JETTY - BSY"
      },
      {
       "expr": "jetty_threads_current{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "JETTY - CUR"
      },
      {
       "expr": "jetty_threads_config_max{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "JETTY - MAX"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "used",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_used\" WHERE (\"area\" = 'heap' ) AND $timeFilter GROUP BY time($__interval) fill(previous)"
      },
      {
       "alias": "committed",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_committed\" WHERE (\"area\" = 'heap' ) AND $timeFilter GROUP BY time($__interval) fill(previous)"
      },
      {
       "alias": "max",
       "query": "SELECT sum(\"value\") FROM \"jvm_memory_max\" WHERE (\"area\" = 'heap' ) AND $timeFilter GROUP BY time($__interval) fill(previous)"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(jvm_memory_committed{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "committed"
      },
      {
       "expr": "sum(jvm_memory_max{application=\"$application\", instance=\"$instance\"})",
       "legendFormat": "max"
      }
     ]
    }
   ]
  }
 ]
}