{
 "title": "DNS metrics - DSB",
 "tags": [ "dhruva" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment filter",
    "query": "show tag values from \"dhruva.dns\" with key = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total SRV & A lookups",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_environment {queryType: $tag_queryType}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND $timeFilter GROUP BY time($__interval), \"queryType\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS lookup time stats",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms", "label": "dnsProcessingTime" }
   ],
   "targets": [
    {
     "alias": "$tag_environment {queryType: $tag_queryType}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"dnsProcessingDelayMillis\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/AND $timeFilter GROUP BY \"environment\", \"queryType\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "A lookup success rate",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "dns.a.success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.a.success\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'A' AND \"failureReason\" !~ /./ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "dns.a.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.a.total\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'A' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "A lookup failure rate",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "dns.a.failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.a.failure\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'A' AND \"failureReason\" =~ /./ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "dns.a.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.a.total\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'A' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Types of A lookup failure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_environment {failureReason: $tag_failureReason}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'A' AND \"failureReason\" =~ /./ AND $timeFilter GROUP BY time($__interval), \"failureReason\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "A lookup failure details",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"query\", \"queryType\", \"dnsProcessingDelayMillis\", \"failureReason\", \"environment\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'A' AND \"failureReason\" =~ /./ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SRV lookup success rate",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "dns.srv.success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.srv.success\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'SRV' AND \"failureReason\" !~ /./ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "dns.srv.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.srv.total\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'SRV' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SRV lookup failure rate",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "dns.srv.failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.srv.failure\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'SRV' AND \"failureReason\" =~ /./ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "dns.srv.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") AS \"dns.srv.total\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'SRV' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Types of SRV lookup failure",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_environment {failureReason: $tag_failureReason}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\") FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'SRV' AND \"failureReason\" =~ /./ AND $timeFilter GROUP BY time($__interval), \"failureReason\", \"environment\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SRV lookup failure details",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"query\", \"queryType\", \"dnsProcessingDelayMillis\", \"failureReason\", \"environment\" FROM \"dhruva.dns\" WHERE \"environment\" =~ /$env/ AND \"queryType\" = 'SRV' AND \"failureReason\" =~ /./ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}