{
 "title": "Executor Metrics - DSB",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env_host_query_str",
    "label": "Environment",
    "query": "show tag values from \"monitored_executor\" with key = \"environment\""
   }
  ]
 },
 "panels": [
  { "title": "Monitored executor metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thread pool queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"queue\") FROM \"monitored_executor\" WHERE  \"environment\" =~ /$env_host_query_str/ AND \"service\" =~ /(?i)dhruva/ AND $timeFilter GROUP BY time($interval), \"environment\", \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Thread pool submissions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "submissions/min" }
   ],
   "targets": [
    {
     "aggr_query": "SELECT mean(\"submitted\") FROM \"monitored_executor\" WHERE \"environment\" =~ /$env_host_query_str/ AND \"service\" =~ /(?i)dhruva/ AND $timeFilter GROUP BY time(1m), \"environment\", \"pool_name\" fill(null)",
     "alias": "$tag_environment $tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "executor",
     "query": "SELECT mean(\"submitted\") FROM \"monitored_executor\" WHERE \"environment\" =~ /$env_host_query_str/ AND \"service\" =~ /(?i)dhruva/ AND $timeFilter GROUP BY time(1m), \"environment\", \"pool_name\" fill(null)\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Reactive Scheduler metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Task Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "completed by {{$tag_reactor_scheduler_id}}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"executor_completed\"  WHERE  \"servicename\" = 'dhruva' and $timeFilter GROUP BY time(1m),\"reactor_scheduler_id\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "queued in {{$tag_reactor_scheduler_id}}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"executor_queued\"  WHERE  \"servicename\" = 'dhruva' and  $timeFilter GROUP BY time($__interval),\"reactor_scheduler_id\" fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task execution latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{$tag_reactor_scheduler_id}}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"upper\") FROM \"executor\" WHERE \"servicename\" = 'dhruva' and $timeFilter GROUP BY time($__interval), \"reactor_scheduler_id\" fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}