{
 "title": "Monitored Executor Metrics",
 "tags": [
  "dhruva",
  "devops"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "SHOW TAG VALUES FROM \"monitored_executor\" WITH KEY = \"environment\" WHERE \"service\" = 'dhruva'"
   },
   {
    "name": "pools",
    "label": "Pool(s) to Display",
    "query": "SHOW TAG VALUES FROM \"monitored_executor\" WITH KEY = \"pool_name\" WHERE \"service\" = 'dhruva'"
   },
   { "name": "service", "label": "service", "query": "dhruva" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Cluster Thread pool queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(max(\"queue\"), 5) FROM \"monitored_executor\" WHERE \"service\" =~ /(?i)dhruva/ AND $timeFilter GROUP BY time(1m), \"environment\", \"pool_name\" fill(0) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Cluster Thread pool rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(max(\"rejected\"), 5) FROM \"monitored_executor\" WHERE \"service\" =~ /(?i)dhruva/ AND $timeFilter GROUP BY \"meta_datacenter\", time(1m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Working Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queued Threads",
   "type": "graph",
   "description": "The panel shows the executor queue max value and percentage it is in use atm.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"queue\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    },
    {
     "alias": "Queue Max",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"queue_max\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "queue" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    },
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (max(\"queue\") / max(\"queue_max\")) * 100 \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running Threads",
   "type": "graph",
   "description": "Shows available and currently running threads.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"running\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND  $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Locus" }
     ]
    },
    {
     "alias": "Max Threads",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"pool_max\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND  $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Locus" }
     ]
    }
   ]
  },
  { "title": "Rejected Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Rejected Threads",
   "type": "graph",
   "description": "The panel show rejected threads.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"rejected\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "rejected" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    }
   ]
  },
  { "title": "Submitted/Completed Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Submitted Threads",
   "type": "graph",
   "description": "The panel shows submitted threads.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"submitted\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "submitted" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    }
   ]
  },
  {
   "title": "Completed Threads",
   "type": "graph",
   "description": "The panel shows compleated threads.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"completed\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "completed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    }
   ]
  },
  { "title": "Thread/Queue Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Mean Thread Duration",
   "type": "graph",
   "description": "The panel shows mean thread duration.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT mean(\"duration\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    }
   ]
  },
  {
   "title": "Mean Queue Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT mean(\"duration_enqueued\") \nFROM \"monitored_executor\" \nWHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter \nGROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Calliope" }
     ]
    }
   ]
  },
  { "title": "Thread Pool Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Thread Pool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT mean(\"pool_size\") FROM \"monitored_executor\" WHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter GROUP BY time($interval), \"pool_name\" fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Locus" }
     ]
    }
   ]
  },
  { "title": "Working Threads per Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Threads Running per Instance",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool_name $tag_instance_index",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pool_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monitored_executor",
     "query": "SELECT max(\"running\") FROM \"monitored_executor\" WHERE \"environment\" =~ /$env/ AND \"service\" =~ /$service/ AND \"pool_name\" =~ /$pools/ AND $timeFilter GROUP BY time($interval), \"pool_name\", \"instance_index\" fill(null)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=", "value": "Locus" }
     ]
    }
   ]
  }
 ]
}