{
 "title": "Trunk Monitoring Metrics",
 "tags": [ "dhruva" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "trunkName",
    "label": "trunkName",
    "query": "show tag values from \"dhruva.trunkMetric\" with key = \"trunk\""
   },
   {
    "name": "cluster",
    "label": "clusterName",
    "query": "show tag values from \"dhruva.trunkMetric\" with key=\"environment\" "
   },
   {
    "name": "instance",
    "label": "Instance Name",
    "query": "show tag values from \"trunkServerGroupstatus\" with key = \"instanceName\" WHERE \"environment\" =~ /$cluster/ AND time >= now()"
   },
   {
    "name": "sgName",
    "label": "sgName",
    "query": "show tag values from \"dhruva.sgeMetric\" with key = \"sgName\""
   }
  ]
 },
 "panels": [
  {
   "title": "SGStatus",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sgName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT status as \"status\" FROM \"dhruva.sgMetric\" WHERE $timeFilter  AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/ AND \"sgName\" =~ /$sgName/ GROUP BY sgName ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SGEStatus",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "$tag_sgeName-$tag_sgName",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT status as \"status\" FROM \"dhruva.sgeMetric\" WHERE $timeFilter  AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  AND \"sgName\" =~ /$sgName/ GROUP BY \"sgeName\", \"sgName\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Inbound & Outbound CPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Inbound CPS",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_trunk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"inboundCount\") FROM \"dhruva.trunkcps\" WHERE $timeFilter AND \"environment\" =~ /$cluster/  GROUP BY \"trunk\",  time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outbound CPS",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_trunk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"outboundCount\") FROM \"dhruva.trunkcps\" WHERE $timeFilter  AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/ GROUP BY  \"trunk\", \"outboundCount\", time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "repeat": "trunkName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Trunk & Element Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Trunk Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "alias": "$tag_trunk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"status\" FROM \"trunkstatus\" WHERE $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/ GROUP BY \"trunk\"  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SG Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "alias": "$tag_trunkServerGroup",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"status\" FROM \"trunkServerGroupstatus\" WHERE $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/ GROUP BY \"trunkServerGroup\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trunk SG Mapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  trunkName as Trunk FROM \"trunkstatus\" WHERE time > now() - 4m AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  mapping as Map FROM \"trunkstatus\" WHERE time > now() - 4m AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}