{
 "title": "Trunk Monitoring Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "trunkName",
    "label": "trunkName",
    "query": "show tag values from \"dhruva.trunkMetric\" with key = \"trunk\""
   },
   {
    "name": "cluster",
    "label": "clusterName",
    "query": "show tag values from \"dhruva.trunkMetric\" with key=\"environment\" "
   },
   {
    "name": "instance",
    "label": "Instance Name",
    "query": "show tag values from \"trunkServerGroupstatus\" with key = \"instanceName\" WHERE \"environment\" =~ /$cluster/ AND time >= now()"
   }
  ]
 },
 "panels": [
  { "title": "Trunk Failure v/s Success ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Failure",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "repeat": "trunkName",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"failure\" from \"dhruva.trunkMetric\" WHERE  \"response\" != 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Failure",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"failure\" from \"dhruva.trunkMetric\" WHERE  \"response\" != 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Failure",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"failure\" from \"dhruva.trunkMetric\" WHERE  \"response\" != 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Failure",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "failure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"failure\" from \"dhruva.trunkMetric\" WHERE  \"response\" != 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/\n ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Success dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "repeat": "trunkName",
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"success\" from \"dhruva.trunkMetric\" WHERE  \"response\" = 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Success dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"success\" from \"dhruva.trunkMetric\" WHERE  \"response\" = 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Success dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"success\" from \"dhruva.trunkMetric\" WHERE  \"response\" = 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "blackmirror1-singlestat-math-panel",
   "description": "Success dashboard",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"success\" from \"dhruva.trunkMetric\" WHERE  \"response\" = 200 AND \"trunk\" =~ /$trunkName/  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(\"callId\")   as \"total\" from \"dhruva.trunkMetric\" WHERE \"trunk\" =~ /$trunkName/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Inbound & Outbound CPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Inbound CPS",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_trunk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"inboundCount\") FROM \"dhruva.trunkcps\" WHERE $timeFilter AND \"environment\" =~ /$cluster/  GROUP BY \"trunk\",  time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outbound CPS",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_trunk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"outboundCount\") FROM \"dhruva.trunkcps\" WHERE $timeFilter  AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/ GROUP BY  \"trunk\", \"outboundCount\", time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "repeat": "trunkName",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$trunkName",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_serverGroupElement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(lbcount) FROM \"dhruva.trunkLbs\" where \"trunk\" =~/$trunkName/ AND $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/  group by serverGroupElement ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Trunk & Element Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Trunk Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "$tag_trunk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"status\" FROM \"trunkstatus\" WHERE $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/ GROUP BY \"trunk\"  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SG Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "alias": "$tag_trunkServerGroup",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"status\" FROM \"trunkServerGroupstatus\" WHERE $timeFilter AND \"environment\" =~ /$cluster/ AND \"instanceName\" =~ /$instance/ GROUP BY \"trunkServerGroup\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trunk SG Mapping",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  trunkName as Trunk FROM \"trunkstatus\" WHERE time > now() - 3m AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  mapping as Map FROM \"trunkstatus\" WHERE time > now() - 3m AND \"environment\" =~ /$cluster/  AND \"instanceName\" =~ /$instance/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}