{
 "title": "DSB App JVM metrics",
 "description": "Dashboard for Spring Boot App JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory(Free)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_FreePhysicalMemorySize{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}/java_lang_OperatingSystem_TotalPhysicalMemorySize{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"})*100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(java_lang_OperatingSystem_SystemCpuLoad{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[5m]) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{kubernetes_namespace=\"$namespace\", kubernetes_pod_name=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_SystemCpuLoad{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"} * 100",
     "legendFormat": "system"
    },
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"} * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "process",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_OpenFileDescriptorCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "descriptors",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Garbage collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_GarbageCollector_CollectionCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC time / 5 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(java_lang_GarbageCollector_CollectionCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Class loading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_ClassLoading_TotalLoadedClassCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  { "title": "MemoryPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_CollectionUsage_used{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Pool Committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_MemoryPool_CollectionUsage_committed{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=\"$pod\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Memory Heap /NonHeap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Heap memory "
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Non heap memory "
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_committed{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Heap memory"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_committed{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "Non heap memory"
    }
   ]
  },
  { "title": "Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "java_lang_Threading_DaemonThreadCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat Request Processor bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Tomcat_GlobalRequestProcessor_bytesReceived{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "{{name}} recv"
      },
      {
       "expr": "increase(Tomcat_GlobalRequestProcessor_bytesSent{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "{{name}} sent"
      }
     ]
    },
    {
     "title": "Tomcat Request Processor count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Tomcat_GlobalRequestProcessor_requestCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "{{name}} count"
      },
      {
       "expr": "increase(Tomcat_GlobalRequestProcessor_errorCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "{{name}} error"
      }
     ]
    },
    {
     "title": "Top 5 servlets average processing time per request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(Tomcat_Servlet_processingTime{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])/increase(Tomcat_Servlet_requestCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
      }
     ]
    },
    {
     "title": "Tomcat Threadpool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(Tomcat_ThreadPool_currentThreadCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "current: {{name}}"
      },
      {
       "expr": "increase(Tomcat_ThreadPool_currentThreadsBusy{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "busy: {{name}}"
      },
      {
       "expr": "increase(Tomcat_ThreadPool_connectionCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "connection: {{name}}"
      },
      {
       "expr": "increase(Tomcat_ThreadPool_keepAliveCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "keepalive: {{name}}"
      }
     ]
    },
    {
     "title": "Average processing time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "increase(Tomcat_Servlet_processingTime{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m])",
       "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
      }
     ]
    },
    {
     "title": "Tomcat manager sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(Tomcat_Manager_expiredSessions{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "expired"
      },
      {
       "expr": "sum(increase(Tomcat_Manager_rejectedSessions{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "rejected"
      }
     ]
    },
    {
     "title": "Top 5 servlet request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(Tomcat_Servlet_requestCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
      }
     ]
    },
    {
     "title": "Top 5 servlet error count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(Tomcat_Servlet_errorCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}[1m]))",
       "legendFormat": "WebModule: {{WebModule}} Name: {{name}}"
      }
     ]
    },
    {
     "title": "Max threads",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Tomcat_ThreadPool_maxThreads{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "name: {{name}}"
      }
     ]
    },
    {
     "title": "Accept count",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Tomcat_Connector_acceptCount{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Min spare threads",
     "type": "graph",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "Tomcat_ThreadPool_minSpareThreads{kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod\"}",
       "legendFormat": "name: {{name}}"
      }
     ]
    }
   ]
  }
 ]
}