spring:
  cloud:
    kubernetes:
      config:
        namespace: default
        sources:
          - name: server
          - name: servergroup

      reload:
        enabled: true
common:
  listen-points:
    - name: "SampleNetwork" #DO not change this name as it's embedded into sample-app
      port: 5062
      transport: TCP
      hostIPAddress: "127.0.0.1"
