app:
  networkPSTN: &netsp "net_sp"
  networkB2B: &netb2b "net_antares"
  networkCallingCore: &netcc "net_cc"
  b2b-egress: "Antares"
  calling-egress: "NS"
  pstn-ingress: "CcpFusionUS"
  maintenance:
    enabled: false
    description: "DSB is in maintenance"
  rateLimitPolicy:
    - name: &rateLimitPolicyPstn "rateLimitPolicyPstn"
      allowList: ['1.1.1.1', '2.2.2.2']
      type: network
      rateLimit:
        permits: 200
        interval: 60s
    - name: &rateLimitPolicyGlobal "rateLimitPolicyGlobal"
      allowList: ["3.3.3.3"]
      denyList: ["4.4.4.4"]
      autoBuild: true
      type: global
      rateLimit:
        permits: 1000
        interval: 60s

  rateLimiter:
    rateLimitPolicyPstn:
      policyName: *rateLimitPolicyPstn
      networks: [*netsp]
common:
  maintenancePolicy:
    mPolicy1:
      name: &mPolicy1 mPolicy1
      dropMsgTypes: ['OPTIONS']
      responseCode: 400
    mPolicy2:
      name: &mPolicy2 mPolicy2
      responseCode: 400
    globalPolicy:
      name: &globalPolicy global
      responseCode: 503
  customMonitorPingInitialDelayInSec: 5
  customMonitorPingPeriodInSec: 30
  listenPoints:
    - name: *netsp
      port: 5065
      transport: UDP
      hostIPAddress: "127.0.0.1"
      enableRateLimiter: true
      pingTimeOut: 500
    - name: *netb2b
      port: 5062
      transport: UDP
      hostIPAddress: "127.0.0.1"
      pingTimeOut: 500
    - name: *netcc
      port: 5080
      transport: UDP
      hostIPAddress: "127.0.0.1"
      pingTimeOut: 500
  serverGroups:
    UsPoolA:
      name: &UsPoolA UsPoolA
      hostName: "UsPoolA"
      networkName: *netsp
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 8001
          priority: 5
          weight: 100
        - ipAddress: "127.0.0.1"
          port: 8002
          priority: 10
          weight: 100
      routePolicy: policy1
      optionsPingPolicy: opPolicy1
    UsPoolB:
      name: &UsPoolB UsPoolB
      hostName: "UsPoolB"
      networkName: *netsp
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 8000
          priority: 10
          weight: 100
      routePolicy: policy1
      optionsPingPolicy: opPolicy1
    InPoolA:
      name: &InPoolA InPoolA
      hostName: "InPoolA"
      networkName: *netsp
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 4000
          priority: 10
          weight: 100
      routePolicy: policy1
      optionsPingPolicy: opPolicy1
    Antares:
      name: &Antares Antares
      hostName: "test.beech.com"
      networkName: *netb2b
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 6000
          priority: 10
          weight: 100
      routePolicy: policy1
      optionsPingPolicy: opPolicy1
    NS1:
      name: &NS1 NS1
      hostName: "test1.ns.cisco.com"
      networkName: *netcc
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 7000
          priority: 10
          weight: 100
      routePolicy: policy1
      optionsPingPolicy: opPolicy1
  routePolicy:
    policy1:
      name: policy1
      failoverResponseCodes:
        - 501
        - 502
        - 404
      circuitBreakConfig:
        waitDurationInOpenState: 10
        slidingWindowSize: 2
        failureThresholdRate: 50
        permittedNumberOfCallsInHAlfOpenState: 1
        slidingWindowType: COUNT_BASED

  optionsPingPolicy:
    opPolicy1:
      name: opPolicy1
      failureResponseCodes:
        - 501
        - 502
        - 503
      upTimeInterval: 30000
      downTimeInterval: 5000

trunk:
  PSTN:
    CcpFusionUS:
      name: CcpFusionUS
      ingress:
        name: ingress1
      egress:
        routePolicy: policy1
        lbType: weight
        selector:
          dtg: CcpFusionUS
        serverGroups:
          - sg: *UsPoolA
            priority: 20
            weight: 100
          - sg: *UsPoolB
            priority: 10
            weight: 100
    CcpFusionIN:
      name: CcpFusionIN
      ingress:
        name: ingress1
      egress:
        selector:
          dtg: CcpFusionIN
        lbType: weight
        serverGroups:
          - sg: *InPoolA
            priority: 10
            weight: 100
  B2B:
    Antares:
      name: Antares
      ingress:
        name: antares_ig
      egress:
        lbType: ONCE
        serverGroups:
          - sg: *Antares
            priority: 10
            weight: 100
  CallingCore:
    NS:
      name: NS
      ingress:
        name: ns_ig
        maintenancePolicy: *mPolicy1
      egress:
        lbType: ONCE
        serverGroups:
          - sg: *NS1
            priority: 10
            weight: 100