app:
  networkIn: &netIn "net_in"
  networkOut: &netOut "net_out"
  default-egress: "Default"
common:
  listenPoints:
    - name: *netIn
      port: 5060
      transport: UDP
      hostIPAddress: "127.0.0.1"
    - name: *netOut
      port: 5070
      transport: UDP
      hostIPAddress: "127.0.0.1"
  serverGroups:
    DefaultSg1:
      name: &DefaultSg1 DefaultSg1
      hostName: "DefaultSg1"
      networkName: *netOut
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 6060
          priority: 10
          weight: 100
        - ipAddress: "127.0.0.1"
          port: 6061
          priority: 5
          weight: 100
      routePolicy: policy1
    DefaultSg2:
      name: &DefaultSg2 DefaultSg2
      hostName: "DefaultSg2"
      networkName: *netOut
      lbType: weight
      elements:
        - ipAddress: "127.0.0.1"
          port: 6062
          priority: 10
          weight: 100
        - ipAddress: "127.0.0.1"
          port: 6063
          priority: 5
          weight: 100
      routePolicy: policy1
  routePolicy:
    p1:
      name: p1
      failoverResponseCodes:
        - 501
        - 502
        - 503
trunk:
  DEFAULT:
    Default:
      name: Default
      egress:
        routePolicy: p1
        lbType: weight
        serverGroups:
          - sg: *DefaultSg1
            weight: 100
            priority: 5
          - sg: *DefaultSg2
            weight: 100
            priority: 10