{
 "title": "CallingApp-KPIs",
 "tags": [ "dhruva" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "show tag values from \"dhruva.call.latency\" with key = \"environment\""
   },
   { "name": "service", "label": "Service Name", "query": "dhruva" },
   { "name": "transport", "label": "transport", "query": "TCP,UDP,NONE" },
   { "name": "ismidCall", "label": "isMidCall", "query": "false,true" }
  ]
 },
 "panels": [
  {
   "title": "calling App Service Availability ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"availability\") FROM \"dhruva.service.health\" WHERE \"servicename\" = '$service' AND \"environment\" =~ /$env/ AND $timeFilter GROUP BY time($interval), environment  fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error rate(By Dhruva)",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "invite.fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'true') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "invite.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"callId\") AS \"invite.total\" FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'REQUEST' AND \"method\" = 'INVITE' AND \"direction\" = 'IN') AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "95th Percentile Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\",95) FROM \"dhruva.call.latency\" WHERE $timeFilter AND \"environment\" =~ /$env/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "99th percentile latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "99th Percentile Latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT percentile(\"duration\",99) FROM \"dhruva.call.latency\" WHERE $timeFilter AND \"environment\" =~ /$env/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}