{
 "title": "Dhruva Service Availibility",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env_host_query_str",
    "label": "Environment Filter",
    "query": "show tag values from \"dhruva.service.health\" with key = \"environment\""
   },
   { "name": "service", "label": "Service Name", "query": "dhruva" }
  ]
 },
 "panels": [
  {
   "title": "DSB Service Availability ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"availability\") FROM \"dhruva.service.health\" WHERE \"servicename\" = '$service' AND \"environment\" =~ /$env_host_query_str/ AND $timeFilter GROUP BY time($interval), environment  fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DSB Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggr_query": "SELECT max(\"availability\") FROM \"l2sip.health.l2sip.v4\" WHERE \"servicename\" = 'l2sip' AND \"environment\" =~ /$env_host_query_str/ AND $timeFilter GROUP BY time($interval), environment fill(null)",
     "alias": "Availability [Instance: $tag_instanceName]",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "l2sip.health.l2sip",
     "query": "SELECT max(\"availability\") FROM \"dhruva.service.health\" WHERE \"servicename\" = '$service' AND \"environment\" =~ /$env_host_query_str/ AND $timeFilter GROUP BY time($interval), environment, instanceName fill(0)",
     "select": [
      [
       { "params": [ "availability" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream Service Availability",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"availability\") FROM \"dhruva.service.upstream.health\" WHERE \"servicename\" = '$service' AND \"environment\" =~ /$env_host_query_str/ AND $timeFilter GROUP BY time($interval), \"name\", environment  fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upstream availibility by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggr_query": "SELECT 100.0 - mean(\"availability\") FROM \"l2sip.health.upstream.v4\" WHERE \"servicename\" = 'l2sip' AND \"environment\" =~ /$env_host_query_str/ AND $timeFilter GROUP BY \"name\", \"environment\", time($interval) fill(null)",
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"availability\") FROM \"dhruva.service.upstream.health\" WHERE \"servicename\" = '$service' AND \"environment\" =~ /$env_host_query_str/ AND $timeFilter GROUP BY \"name\", \"environment\", time($interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}