{
 "title": "Error Rate KPI",
 "tags": [ "dhruva" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment Filter",
    "query": "show tag values from \"dhruva.sipMessage\" with key = \"environment\""
   },
   { "name": "transport", "label": "transport", "query": "TCP,UDP,NONE" },
   { "name": "ismidcall", "label": "isMidCall", "query": "false,true" }
  ]
 },
 "panels": [
  { "title": "Call Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Invites",
   "type": "stat",
   "description": "Total Number of calls",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'REQUEST' AND \"method\" = 'INVITE' AND \"direction\" = 'IN') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total calls success",
   "type": "stat",
   "description": "Total number of calls accepted by dhruva",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" = 200 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'false') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total 4xx ",
   "type": "stat",
   "description": "Total Number of dhruva client failure responses (4xx)",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" < 500 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total 5xx",
   "type": "stat",
   "description": "Total Number of dhruva server failure responses 5xx",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 500 AND \"responseCode\" < 600 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total 6xx",
   "type": "stat",
   "description": "Total Number of dhruva global failure responses 6xx",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 600 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Dhruva Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total calls rejected by Dhruva",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'true') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total calls rejected by Dhruva",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 6 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_environment {method: $tag_method CallType: $tag_callType}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'true') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter GROUP BY time($__interval), \"method\", \"environment\", \"callType\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error rate(By Dhruva)",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "invite.fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'true') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "invite.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'REQUEST' AND \"method\" = 'INVITE' AND \"direction\" = 'IN') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dhruva rejected call details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"callId\", \"method\", \"transport\" , \"responseReason\" , \"additionalDetails\" FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'true') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Downstream Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total calls rejected by Downstream",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'false') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total calls rejected by downstream service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 24 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_environment {method: $tag_method CallType: $tag_callType}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'false') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter GROUP BY time($__interval), \"environment\", \"method\", \"callType\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error rate(By Downstream)",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "invite.fail",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'false') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "invite.total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'REQUEST' AND \"method\" = 'INVITE' AND \"direction\" = 'IN') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Downstream rejected call details",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"callId\", \"method\",  \"transport\" , \"responseReason\"  FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 AND \"responseCode\" <= 608 AND \"direction\" = 'OUT' AND \"cSeq\" = 'INVITE' AND \"isInternallyGenerated\" = 'false') AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Error Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "4XX responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "4xx response count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 400 and \"responseCode\" < 500 AND \"cSeq\" = 'INVITE' ) AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter group by time(10m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "5XX responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "5xx response count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 500 and \"responseCode\" < 600 AND \"cSeq\" = 'INVITE' ) AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter group by time(10m)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "6XX responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "6xx response count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"callId\")) FROM \"dhruva.sipMessage\" WHERE (\"messageType\" = 'RESPONSE' AND \"responseCode\" >= 600 and \"responseCode\" <= 608 AND \"cSeq\" = 'INVITE' ) AND \"isMidCall\" =~ /$ismidcall/ AND \"environment\" =~ /$env/ AND \"transport\" =~ /$transport/ AND $timeFilter group by time(10m)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}