{
 "title": "ServerGroup Down Alerting ENV - wdfwwxc-int-2",
 "description": "Alerting for servergroup",
 "tags": [
  "dhruva",
  "alerting"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ServerGroup - wdfwwxc-int-2 : Atl-Atlanta",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'Atl-Atlanta'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : Ewr-NewJersey",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'Ewr-NewJersey'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-1'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-1-AU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-1-AU'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-11",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-11'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-2'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-3'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-4'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-5'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-6",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-6'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-7",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-7'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-8",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-8'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-AS-9",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-AS-9'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-NS-AU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-NS-AU'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-NS-Sip",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-NS-Sip'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS2-NS-Usr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS2-NS-Usr'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-1'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-1-EU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-1-EU'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-11",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-11'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-2'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-3",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-3'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-4",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-4'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-5",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-5'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-6",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-6'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-7",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-7'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-8",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-8'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-AS-9",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-AS-9'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-NS-EU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-NS-EU'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-NS-Sip",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-NS-Sip'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : HS3-NS-Usr",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'HS3-NS-Usr'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : Kamailio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'Kamailio'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : Telnyx-Chicago",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'Telnyx-Chicago'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ServerGroup - wdfwwxc-int-2 : Telnyx-Washington",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "query": "SELECT status FROM \"dhruva.sgMetric\" WHERE \"environment\" = 'wdfwwxc-int-2' AND \"sgName\" = 'Telnyx-Washington'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}