common:
  serverGroups:
    SG1:
      name: SG1
      networkName: TCPNetwork
      lbType: HIGHEST_Q
      pingOn: true
      elements:
        - ipAddress: "10.78.98.54"
          port: 5061
          transport: TCP
          qValue: 0.9
          weight: 10
        - ipAddress: "10.78.98.54"
          port: 5062
          transport: TCP
          qValue: 0.9
          weight: 10
      sgPolicy: policy1
  listen-points:
    - name: "TCPNetwork"
      port: 5061
      transport: TCP
      hostIPAddress: "10.227.233.14"
      recordRoute: false
      attachExternalIP: true
      tlsAuthType: client
      enableCertService: true
  sgPolicy:
    policy1:
      name: policy1
      failoverResponseCodes:
        - 501
        - 502
        - 503